apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hpl5dfgqz-java-springboot 
  janus-idp.io/tekton: hpl5dfgqz-java-springboot
  backstage.io/kubernetes-id: hpl5dfgqz-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hpl5dfgqz-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml